import type { Metadata } from "next";

import "@/shared/styles/globals.css";
import Providers from "@/shared/utils/Providers";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn />
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
